export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REG_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
export const SANATOR_ROUTE = '/sanator'
export const ORDER_ROUTE = '/order'